spaces = ' ' * 25
print('%s 12 butts wynd' % spaces)
print('%s Twinkebottum Health' % spaces)
print('%s West snorting % spaces)
print()
print()
print('Dear sir')
print()
print('I wish to report that titles are missing from the')
print('outside the toilet root.')
print('I think it was bad wind the order night that blew them away.')
print()
print('Regards')
print('Malcolm Dithering')